name: mi_entorno
channels:
  - defaults
dependencies:
  - python==3.9
  - requests==2.31.0
  - pip

  - pip:
    - PyYAML==6.0.1
    - langchain==0.0.251
    - torch==2.0.1
    - chromadb==0.4.4
    - nums_from_string==0.1.2
    - openai==0.27.8
    - rich==13.5.2
    - pypdf==3.15.5
    - tiktoken==0.4.0